### PR TITLE
HD-112913 anytv-mailer > support attaching files > fixes

### PR DESCRIPTION
**Pull request by amr-rubix**
[HD-112913 > anytv-mailer > support attaching files > fixes](https://freedom.myjetbrains.com/youtrack/issue/HD-112913)

After releasing the new version of anytv-mailer, there were some code missing and was not caught due to testing directly on the package files inside earnings project, which was not reflecting the real changes on the package itself. 

Changes needed.
1. add attachments definition in constructor
2. update readme
3. test on local version of the package  `"anytv-mailer": "file:../anytv-mailer"`

## Checklist

- [ ] bugfix
- [x] new feature
- [ ] breaking change
- [ ] added unit tests
- [x] changes introduced has been discussed and approved
- [x] requires manual testing
- [ ] documentation has been updated

### CODE REVIEW

**Review by jethromalate — APPROVED** [review]

**Review by pandafox — APPROVED** [review]
Please create associate ticket as well and we'd need a new version.

How did this pass testing?

**Comment by cedricabuso** [comment]
@pandafox testing is still being tried in dev branch in earnings actually

**Review by cedricabuso — APPROVED** [review]

**Comment by amr-rubix** [comment]
@pandafox @cedricabuso @jethromalate 

Testing process:

fetch anytv-mailer package locally 


Screen Shot 2021-12-20 at 3 43 19 PM

created a test route for sending email
Screen Shot 2021-12-20 at 3 44 35 PM

mail received successfully with attached file
Screen Shot 2021-12-20 at 3 42 54 PM

**Review by annefrmarinas — APPROVED** [review]

**Comment by jethromalate** [comment]
image

**Pull request merged**
